### ISSUE TITLE
Wrong resolution detection and scaling with DOS/Windows resolution 1024x768x32 (60hz)

### ISSUE THREAD

**Issue by h0ly0ne** [marqs85/ossc_pro#5] opened 2024-04-06 10:16 UTC
When using 1024x768 in 32bit with 60hz display set the signal coming over VGA connector seems to be detected as DTV 720p_60 (shown under scaler settings->adv. timing and therefor has hidden/unviewable area (i am not able to move the complete screen to a fully viewable position) after being scaled up to 1920x1080. In the scaler settings there is also no option to "hardwire" 806-p to a resolution profile (if it is required at all when resolution is detected correct).

In addition 1152x864 in 32bit with 60hz also seems to be detected wrongly as "PC 1024x768_60" and there is also no option to "hardwire" 895-p to a resolution profile.

Just for reference 800x600x32(60) and 1280x1024x32(60) are detected correctly - also there is a hardwire feature missing, but I am able to reposition everything correctly within the default profiles

**Comment by marqs85** [comment] 2024-04-06 12:23
806-p should get mapped to "PC 1024x768_60" preset in SCL & A-LM modes. Which firmware version are you using? Currently 1152x864 does not yet have a dedicated sampling preset, but it should be possible to tweak the automatically selected preset for 1152x864 timings via Adv. timing menu.

**Comment by h0ly0ne** [comment] 2024-04-06 15:23
Currently I'm using the most recent v0.74. 806-p seems to be incorrectly mapped then for me - see attached screenshot of the issue. Just for completeness I am using VGA Connected @AV3_RGBHV (only Input-Source that seems to work for me) and using only "Scaler"-Mode.

1024x768@60hz (Win98SE):
![grafik](https://github.com/marqs85/ossc_pro/assets/32588743/2cb9ac99-86ed-4df5-b41b-949dfc6badb5)

1024x768@60hz (BIOS/DOS):
![grafik](https://github.com/marqs85/ossc_pro/assets/32588743/0933ef24-7368-4134-afb2-ceac067715eb)

**Comment by marqs85** [comment] 2024-04-06 18:42
Can you try resetting the profile from Settings? I think the issue is caused by v_total of the 1024x768_60 sampling preset (which is used when finding the closest match) having got modified when you changed size/position on 1152x864. The code needs to be updated to utilize default value instead during preset selection to avoid this issue.

**Comment by h0ly0ne** [comment] 2024-04-06 23:41
It seems to be some magic - resetting my profile solved the issues with 1024x768_60 automatic detection - is there maybe some "feature" available to modify the profile saved to SD manually (PC, etc.)? As I'll start now to change all resolution now again to be correct and it would be a pain if i have to that again when some "problems" occur.

**Comment by marqs85** [comment] 2024-04-07 16:03
The issue should be fixed in next firmware which is correctly able to use your existing preset table. However, if the firmware also adds new modes to the default table (like 1152x864), then it's not able to use a version saved with earlier firmware. Having backwards & forwards compatible tables would be great but needs a lot more effort to ensure robust handling.

**Comment by marqs85** [comment] 2024-04-28 21:15
Fixed in ac95ced0f9b79a02fafd150b940f65e02601b6a7

**Closed as completed by marqs85** 2024-04-28 21:15 UTC
