### ISSUE TITLE
[I+] - Info button on remote control - not working anymore ?

### ISSUE THREAD

**Issue by onthewaveagain** [marqs85/ossc_pro#21] opened 2024-09-08 09:22 UTC
Looks like when the  Info button is pressed on the remote control, nothing shows up on screen. Think it worked with previous firmware.

**Comment by marqs85** [comment] 2024-09-08 16:59
Perhaps a duplicate of [this](https://github.com/marqs85/ossc/issues/112)?

**Comment by onthewaveagain** [comment] 2024-09-08 20:16
yes. I actually forgot that I disabled the OSD status option and it looks like the I+ button is linked to this option.
I think this should not be the case. the I+ button should work all the time regardless of the OSD status option.

**Closed as not planned** 2024-11-01 00:01 UTC
